// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8H95S9IWjz-x2Fgh5ZOmS9sNpWyHxyWs',
    appId: '1:701838962355:web:e6d8aab5a0c0d9aeb48ac6',
    messagingSenderId: '701838962355',
    projectId: 'gnos-app',
    authDomain: 'gnos-app.firebaseapp.com',
    databaseURL: 'https://gnos-app-default-rtdb.firebaseio.com',
    storageBucket: 'gnos-app.firebasestorage.app',
    measurementId: 'G-E3YWJ1G5F7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvmUTUzn1lrnRYn16glVOVV02POhMgUek',
    appId: '1:701838962355:android:d6e9bf25dec90297b48ac6',
    messagingSenderId: '701838962355',
    projectId: 'gnos-app',
    databaseURL: 'https://gnos-app-default-rtdb.firebaseio.com',
    storageBucket: 'gnos-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8H95S9IWjz-x2Fgh5ZOmS9sNpWyHxyWs',
    appId: '1:701838962355:web:989bea8e79d86d93b48ac6',
    messagingSenderId: '701838962355',
    projectId: 'gnos-app',
    authDomain: 'gnos-app.firebaseapp.com',
    databaseURL: 'https://gnos-app-default-rtdb.firebaseio.com',
    storageBucket: 'gnos-app.firebasestorage.app',
    measurementId: 'G-590VG0N75V',
  );

}